version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ecommerce-network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce-network

  # Product Service
  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - kafka
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ecommerce
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - cassandra
      - kafka
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce-network

  # PostgreSQL
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Cassandra
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=ecommerce_cluster
    networks:
      - ecommerce-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ecommerce-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  cassandra_data: 